name: Botgram shell-bot Runner

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

env:
  GitHubMail: "manofuranium@gmail.com"
  GitHubName: "ElytrA8"

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.SOURCE }} source

      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t personal
          docker image ls

      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i personal

      - name: Workflow Looping
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Looping at $(date -u +%D-%T%P)"
          git push -q https://github.com/${GITHUB_REPOSITORY} HEAD:main
